### ISSUE TITLE
Set link expiry (Direct Access)

### ISSUE THREAD

**Issue by rafal-leap** [f4bsch/DropPHP#14]
Hi mate 

I see you've added a link expiry get but is there a way to do a link expiry set?
I would like to upload the file and set the link expiry date to eg 1Y. Thanks

https://www.dropbox.com/help/5888

**Comment by rafal-leap** [comment]
I Think there is a way based on that:

https://www.dropboxforum.com/hc/en-us/community/posts/202249859-Set-expiration-of-streamble-link-via-media

**Comment by f4bsch** [comment]
This seems not be possible with the Dropbox REST API.

Instead of sharing the Dropbox links you could create a "proxy" with DropPHP. It keeps file names and their expire date in a DB table. On file request it either redirects to the Dropbox file URL (expiring after 4h) or just gives an expired message.

**Comment by rafal-leap** [comment]
There is an easier way which actuality works well. I've managed to use a shared link instead of direct and preg_replace URL from www to dl. This way the links does not expiry. My idea has been based on pancake.io
